const from=jest.fn(),refresh=jest.fn(),stop=jest.fn(),token=jest.fn();
jest.mock('server-only',()=>({}));
jest.mock('@/lib/supabaseAdmin',()=>({supabaseAdmin:{from:(...args:unknown[])=>from(...args)}}));
jest.mock('@/lib/googleCalendarConnection',()=>({googleConnectionAccessToken:(...args:unknown[])=>token(...args),refreshGoogleCalendarConnection:(...args:unknown[])=>refresh(...args)}));
jest.mock('@/lib/googleCalendarProvider',()=>({stopGoogleCalendarWatch:(...args:unknown[])=>stop(...args)}));
import {maintainGoogleCalendarWatches} from '@/lib/googleCalendarReconciliation';
function result(data:unknown){const q:any={then:(resolve:any)=>Promise.resolve({data,error:null}).then(resolve)};for(const key of ['select','eq','lt','order','limit','in','or','update'])q[key]=jest.fn(()=>q);q.single=jest.fn(async()=>({data,error:null}));return q;}
const expired={id:'expired',connection_id:'connection',status:'pending',resource_id:null,expires_at:'2020-01-01T00:00:00Z'};
const retiring={id:'retiring',connection_id:'connection',status:'retiring',resource_id:'resource',expires_at:'2100-01-01T00:00:00Z'};
beforeEach(()=>{jest.resetAllMocks();token.mockResolvedValue('token');refresh.mockResolvedValue(undefined);stop.mockResolvedValue(undefined);});
test('failed renewal still cleans expired channels and reports a retry',async()=>{const saved=result(null);from.mockReturnValueOnce(result([{connection_id:'connection'}])).mockReturnValueOnce(result({creator_id:'creator',status:'connected'})).mockReturnValueOnce(result([expired])).mockReturnValueOnce(saved);refresh.mockRejectedValue(new Error('temporary'));await expect(maintainGoogleCalendarWatches()).rejects.toThrow('retry');expect(refresh).toHaveBeenCalledWith('creator');expect(saved.update).toHaveBeenCalledWith({status:'stopped'});expect(saved.eq).toHaveBeenCalledWith('status','pending');expect(stop).not.toHaveBeenCalled();});
test('one channel stop failure does not prevent other channel cleanup',async()=>{const saved=result(null);from.mockReturnValueOnce(result([])).mockReturnValueOnce(result([retiring,expired])).mockReturnValueOnce(saved);stop.mockRejectedValue(new Error('temporary'));await expect(maintainGoogleCalendarWatches()).rejects.toThrow('retry');expect(stop).toHaveBeenCalledWith('token',expect.objectContaining({id:'retiring',resourceId:'resource'}));expect(saved.eq).toHaveBeenCalledWith('id','expired');});
test('successful renewal and stop retain status guards on channel retirement',async()=>{const saved=result(null);from.mockReturnValueOnce(result([{connection_id:'connection'}])).mockReturnValueOnce(result({creator_id:'creator',status:'connected'})).mockReturnValueOnce(result([retiring])).mockReturnValueOnce(saved);await maintainGoogleCalendarWatches();expect(refresh).toHaveBeenCalledWith('creator');expect(saved.eq).toHaveBeenCalledWith('status','retiring');});
